"""Frases de libros, ciencia, filosofía y oficio que Bit suelta de vez en cuando.

Cada entrada lleva la obra de donde sale; cuando la atribución es tradicional y
no hay una página exacta que señalar, se indica («atribuida»).
Son píldoras de pensamiento para acompañar el estudio a lo largo del día.
"""
import random

# (frase, autor, obra)
CITAS = [
    # =========================================================================
    # LITERATURA UNIVERSAL, POESÍA Y TEATRO
    # =========================================================================
    ("En un lugar de la Mancha, de cuyo nombre no quiero acordarme…",
     "Miguel de Cervantes", "Don Quijote de la Mancha"),
    ("El que lee mucho y anda mucho, ve mucho y sabe mucho.",
     "Miguel de Cervantes", "Don Quijote de la Mancha"),
    ("Sábete, Sancho, que no es un hombre más que otro si no hace más que otro.",
     "Miguel de Cervantes", "Don Quijote de la Mancha"),
    ("La pluma es la lengua del alma.",
     "Miguel de Cervantes", "Don Quijote de la Mancha"),
    ("Muchos años después, frente al pelotón de fusilamiento, el coronel "
     "Aureliano Buendía había de recordar aquella tarde remota en que su padre "
     "lo llevó a conocer el hielo.",
     "Gabriel García Márquez", "Cien años de soledad"),
    ("La vida no es la que uno vivió, sino la que uno recuerda y cómo la recuerda "
     "para contarla.",
     "Gabriel García Márquez", "Vivir para contarla"),
    ("Todas las familias felices se parecen; las infelices lo son cada una a su manera.",
     "León Tolstói", "Ana Karénina"),
    ("Si buscas la perfección, nunca estarás contento.",
     "León Tolstói", "Ana Karénina"),
    ("El secreto de la existencia humana no solo está en vivir, sino en saber "
     "para qué se vive.",
     "Fiódor Dostoievski", "Los hermanos Karamázov"),
    ("El dolor y el sufrimiento son siempre inevitables para una gran inteligencia "
     "y un corazón profundo.",
     "Fiódor Dostoievski", "Crimen y castigo"),
    ("Era el mejor de los tiempos, era el peor de los tiempos.",
     "Charles Dickens", "Historia de dos ciudades"),
    ("Llamadme Ismael.",
     "Herman Melville", "Moby Dick"),
    ("Es una verdad universalmente reconocida que un hombre soltero, poseedor de "
     "una gran fortuna, necesita una esposa.",
     "Jane Austen", "Orgullo y prejuicio"),
    ("La guerra es la paz. La libertad es la esclavitud. La ignorancia es la fuerza.",
     "George Orwell", "1984"),
    ("En una época de engaño universal, decir la verdad es un acto revolucionario.",
     "George Orwell", "atribuida"),
    ("Lo esencial es invisible a los ojos.",
     "Antoine de Saint-Exupéry", "El principito"),
    ("Caminando en línea recta no puede uno llegar muy lejos.",
     "Antoine de Saint-Exupéry", "El principito"),
    ("Un objetivo sin un plan es simplemente un deseo.",
     "Antoine de Saint-Exupéry", "atribuida"),
    ("La perfección se alcanza no cuando no hay nada más que añadir, sino cuando "
     "no queda nada más que quitar.",
     "Antoine de Saint-Exupéry", "Tierra de hombres"),
    ("Un libro debe ser el hacha que rompa el mar helado dentro de nosotros.",
     "Franz Kafka", "Carta a Oskar Pollak, 1904"),
    ("A partir de cierto punto no hay retorno. Ese es el punto que hay que alcanzar.",
     "Franz Kafka", "Aforismos de Zürau"),
    ("El tiempo es la sustancia de que estoy hecho.",
     "Jorge Luis Borges", "Nueva refutación del tiempo"),
    ("Siempre imaginé que el Paraíso sería algún tipo de biblioteca.",
     "Jorge Luis Borges", "Poema de los dones"),
    ("Hay quienes no pueden imaginar un mundo sin pájaros; hay quienes no pueden "
     "imaginar un mundo sin agua; a mí me cuesta imaginar un mundo sin libros.",
     "Jorge Luis Borges", "Borges, oral"),
    ("Caminante, no hay camino, se hace camino al andar.",
     "Antonio Machado", "Campos de Castilla"),
    ("Hoy es siempre todavía.",
     "Antonio Machado", "Nuevas canciones"),
    ("Nosotros, los de entonces, ya no somos los mismos.",
     "Pablo Neruda", "Veinte poemas de amor y una canción desesperada"),
    ("Cuando emprendas el viaje hacia Ítaca, pide que el camino sea largo.",
     "Constantino Cavafis", "Ítaca"),
    ("La felicidad solo es real cuando se comparte.",
     "Christopher McCandless", "citado en Hacia rutas salvajes"),
    ("Andábamos sin buscarnos, pero sabiendo que andábamos para encontrarnos.",
     "Julio Cortázar", "Rayuela"),
    ("Nada está perdido si se tiene el valor de proclamar que todo está perdido "
     "y hay que empezar de nuevo.",
     "Julio Cortázar", "Libro de Manuel"),
    ("El futuro tiene muchos nombres. Para los débiles es lo inalcanzable. "
     "Para los temerosos, lo desconocido. Para los valientes es la oportunidad.",
     "Víctor Hugo", "Los miserables"),
    ("El pájaro rompe el cascarón. El cascarón es el mundo. Quien quiera nacer "
     "tiene que destruir un mundo.",
     "Hermann Hesse", "Demian"),
    ("El saber se puede comunicar, pero la sabiduría no.",
     "Hermann Hesse", "Siddhartha"),
    ("Dentro de veinte años estarás más decepcionado por las cosas que no hiciste "
     "que por las que hiciste.",
     "Mark Twain", "atribuida"),
    ("El hombre no está hecho para la derrota; un hombre puede ser destruido pero no derrotado.",
     "Ernest Hemingway", "El viejo y el mar"),
    ("En mitad del invierno, aprendí por fin que dentro de mí habitaba un verano invencible.",
     "Albert Camus", "El verano"),
    ("El único verdadero viaje de descubrimiento consiste no en buscar nuevos paisajes, "
     "sino en mirar con nuevos ojos.",
     "Marcel Proust", "En busca del tiempo perdido"),
    ("Tengo en mí todos los sueños del mundo.",
     "Fernando Pessoa", "Tabaquería"),
    ("Las ciudades invisibles son un sueño que nace del corazón de las ciudades invivibles.",
     "Italo Calvino", "Las ciudades invisibles"),
    ("Sabemos lo que somos, pero no lo que podemos llegar a ser.",
     "William Shakespeare", "Hamlet"),
    ("El sabio no se sienta a lamentarse, sino que alegremente se pone a reparar el daño.",
     "William Shakespeare", "Enrique VI"),
    ("Sigue tu propio camino y deja que la gente hable.",
     "Dante Alighieri", "La Divina Comedia"),
    ("¿Qué es la vida? Un frenesí. ¿Qué es la vida? Una ilusión, una sombra, una ficción...",
     "Calderón de la Barca", "La vida es sueño"),
    ("Para viajar lejos, no hay mejor nave que un libro.",
     "Emily Dickinson", "Poemas"),
    ("Dos caminos se bifurcaban en un bosque, y yo tomé el menos transitado, "
     "y eso marcó toda la diferencia.",
     "Robert Frost", "El camino no elegido"),
    ("Sé tú mismo; los demás puestos ya están ocupados.",
     "Oscar Wilde", "atribuida"),
    ("La experiencia es simplemente el nombre que damos a nuestros errores.",
     "Oscar Wilde", "El retrato de Dorian Gray"),
    ("Una vez descartado lo imposible, lo que queda, por improbable que parezca, "
     "debe ser la verdad.",
     "Arthur Conan Doyle", "El signo de los cuatro"),
    ("La memoria no es lo que recordamos, sino lo que nos recuerda.",
     "Octavio Paz", "El laberinto de la soledad"),
    ("Cuando creíamos que teníamos todas las respuestas, de pronto, cambiaron todas las preguntas.",
     "Mario Benedetti", "atribuida"),

    # =========================================================================
    # FILOSOFÍA, ESTOICISMO Y HUMANISMO
    # =========================================================================
    ("Todos los hombres desean por naturaleza saber.",
     "Aristóteles", "Metafísica"),
    ("Somos lo que hacemos día a día. De modo que la excelencia no es un acto, sino un hábito.",
     "Aristóteles", "sintetizado por Will Durant"),
    ("Las raíces del estudio son amargas, pero sus frutos son dulces.",
     "Aristóteles", "atribuida"),
    ("La duda es el principio de la sabiduría.",
     "Aristóteles", "atribuida"),
    ("Una vida sin examen no merece ser vivida.",
     "Platón", "Apología de Sócrates"),
    ("Solo sé que no sé nada.",
     "Sócrates", "atribuida"),
    ("Sapere aude: ten el valor de servirte de tu propio entendimiento.",
     "Immanuel Kant", "¿Qué es la Ilustración?"),
    ("Dos cosas llenan el ánimo de admiración y respeto: el cielo estrellado sobre mí "
     "y la ley moral dentro de mí.",
     "Immanuel Kant", "Crítica de la razón práctica"),
    ("Pienso, luego existo.",
     "René Descartes", "Discurso del método"),
    ("Daría todo lo que sé por la mitad de lo que ignoro.",
     "René Descartes", "atribuida"),
    ("El corazón tiene razones que la razón no entiende.",
     "Blaise Pascal", "Pensamientos"),
    ("Vale más saber algo de todo que saberlo todo de una sola cosa.",
     "Blaise Pascal", "Pensamientos"),
    ("Los límites de mi lenguaje son los límites de mi mundo.",
     "Ludwig Wittgenstein", "Tractatus logico-philosophicus"),
    ("De lo que no se puede hablar, hay que callar.",
     "Ludwig Wittgenstein", "Tractatus logico-philosophicus"),
    ("Quien tiene un porqué para vivir puede soportar casi cualquier cómo.",
     "Friedrich Nietzsche", "El ocaso de los ídolos"),
    ("Hay que tener un caos dentro de sí para dar a luz una estrella danzarina.",
     "Friedrich Nietzsche", "Así habló Zaratustra"),
    ("Quien lucha con monstruos debe cuidar de no convertirse en monstruo.",
     "Friedrich Nietzsche", "Más allá del bien y del mal"),
    ("El hombre está condenado a ser libre.",
     "Jean-Paul Sartre", "El existencialismo es un humanismo"),
    ("Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo yo.",
     "José Ortega y Gasset", "Meditaciones del Quijote"),
    ("Mientras enseñamos, aprendemos.",
     "Séneca", "Cartas a Lucilio"),
    ("No aprendemos para la escuela, sino para la vida.",
     "Séneca", "inversión popular de Cartas a Lucilio 106"),
    ("No es que tengamos poco tiempo, sino que perdemos mucho.",
     "Séneca", "De la brevedad de la vida"),
    ("No hay viento favorable para el barco que no sabe adónde va.",
     "Séneca", "Cartas a Lucilio"),
    ("La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.",
     "Séneca", "atribuida"),
    ("El obstáculo en el camino se convierte en el camino.",
     "Marco Aurelio", "Meditaciones"),
    ("No pierdas más tiempo discutiendo lo que debería ser un hombre bueno. Sé uno.",
     "Marco Aurelio", "Meditaciones"),
    ("La felicidad de tu vida depende de la calidad de tus pensamientos.",
     "Marco Aurelio", "Meditaciones"),
    ("Mira hacia adentro. Dentro está la fuente del bien, y volverá a brotar si sigues cavando.",
     "Marco Aurelio", "Meditaciones"),
    ("No nos afecta lo que nos sucede, sino lo que nos decimos sobre lo que sucede.",
     "Epicteto", "Enquiridión"),
    ("No pretendas que las cosas ocurran como deseas; desea que ocurran como ocurren y serás feliz.",
     "Epicteto", "Enquiridión"),
    ("Primero aprende el significado de lo que dices, y luego habla.",
     "Epicteto", "Disertaciones"),
    ("Tenemos dos orejas y una sola boca para escuchar el doble de lo que hablamos.",
     "Zenón de Elea", "atribuida por Diógenes Laercio"),
    ("Un viaje de mil millas comienza con un solo paso.",
     "Lao-Tse", "Tao Te King"),
    ("El que conoce a los demás es sabio; el que se conoce a sí mismo es iluminado.",
     "Lao-Tse", "Tao Te King"),
    ("El hombre que mueve una montaña comienza cargando pequeñas piedras.",
     "Confucio", "Analectas"),
    ("En medio del caos, también hay oportunidad.",
     "Sun Tzu", "El arte de la guerra"),
    ("La estrategia sin táctica es la ruta más lenta hacia la victoria. "
     "Las tácticas sin estrategia son el ruido antes de la derrota.",
     "Sun Tzu", "El arte de la guerra"),
    ("No reír, ni llorar, ni indignarse, sino comprender.",
     "Baruch Spinoza", "Tratado político"),
    ("La vida solo puede ser entendida mirando hacia atrás, pero debe ser vivida mirando hacia adelante.",
     "Søren Kierkegaard", "Diarios"),
    ("La cosa más grande del mundo es saber ser de uno mismo.",
     "Michel de Montaigne", "Ensayos"),
    ("Quien teme padecer ya padece lo que teme.",
     "Michel de Montaigne", "Ensayos"),
    ("Una habitación sin libros es como un cuerpo sin alma.",
     "Marco Tulio Cicerón", "atribuida"),
    ("Si tienes un jardín y una biblioteca, tienes todo lo necesario.",
     "Marco Tulio Cicerón", "Cartas a los amigos"),
    ("Nadie se baña dos veces en el mismo río, porque todo cambia y nada permanece.",
     "Heráclito", "Fragmentos"),
    ("El talento alcanza un objetivo que nadie más puede alcanzar; "
     "el genio alcanza un objetivo que nadie más puede ver.",
     "Arthur Schopenhauer", "El mundo como voluntad y representación"),
    ("El problema del mundo es que los tontos están seguros de sí mismos "
     "y los inteligentes llenos de dudas.",
     "Bertrand Russell", "El triunfo de la estupidez"),
    ("La verdadera ignorancia no es la ausencia de conocimiento, sino la negativa a adquirirlo.",
     "Karl Popper", "La sociedad abierta y sus enemigos"),
    ("No hay barrera, cerradura ni cerrojo que puedas imponer a la libertad de mi mente.",
     "Virginia Woolf", "Una habitación propia"),

    # =========================================================================
    # CIENCIA, FÍSICA, MATEMÁTICAS Y ASTRONOMÍA
    # =========================================================================
    ("Si he visto más lejos, es porque estoy sentado sobre los hombros de gigantes.",
     "Isaac Newton", "Carta a Robert Hooke, 1675"),
    ("Lo que sabemos es una gota de agua; lo que ignoramos es el océano.",
     "Isaac Newton", "atribuida"),
    ("En los campos de la observación, el azar solo favorece a la mente preparada.",
     "Louis Pasteur", "Conferencia en Lille, 1854"),
    ("Nada en la vida debe temerse, solo comprenderse. Ahora es el momento de comprender más, para temer menos.",
     "Marie Curie", "atribuida"),
    ("La imaginación es más importante que el conocimiento.",
     "Albert Einstein", "entrevista en The Saturday Evening Post, 1929"),
    ("Nunca consideres el estudio como una obligación, sino como una oportunidad de entrar en el bello y maravilloso mundo del saber.",
     "Albert Einstein", "atribuida"),
    ("Dios no juega a los dados con el universo.",
     "Albert Einstein", "Carta a Max Born, 1926"),
    ("La mente que se abre a una nueva idea jamás volverá a su tamaño original.",
     "Albert Einstein", "atribuida"),
    ("Somos polvo de estrellas contemplando estrellas.",
     "Carl Sagan", "Cosmos"),
    ("La ciencia es mucho más una forma de pensar que un cuerpo de conocimientos.",
     "Carl Sagan", "El mundo y sus demonios"),
    ("La ausencia de evidencia no es evidencia de ausencia.",
     "Carl Sagan", "El mundo y sus demonios"),
    ("Afirmaciones extraordinarias requieren evidencias extraordinarias.",
     "Carl Sagan", "Cosmos"),
    ("Dadme un punto de apoyo y moveré el mundo.",
     "Arquímedes", "atribuida por Papo de Alejandría"),
    ("Todos los modelos son falsos; algunos son útiles.",
     "George Box", "Robustness in the Strategy of Scientific Model Building"),
    ("No hay nada más práctico que una buena teoría.",
     "Kurt Lewin", "La teoría del campo en la ciencia social"),
    ("El libro de la naturaleza está escrito en el lenguaje de las matemáticas.",
     "Galileo Galilei", "El Ensayador"),
    ("Mide lo que sea medible y haz medible lo que no lo sea.",
     "Galileo Galilei", "atribuida"),
    ("La geometría existía antes de la creación; es coeterna con la mente de Dios.",
     "Johannes Kepler", "Harmonices Mundi"),
    ("Las matemáticas son la reina de las ciencias, y la teoría de números es la reina de las matemáticas.",
     "Carl Friedrich Gauss", "atribuida"),
    ("Debemos saber; sabremos.",
     "David Hilbert", "discurso en Königsberg, 1930"),
    ("El primer principio es no engañarte a ti mismo, y tú eres la persona más fácil de engañar.",
     "Richard Feynman", "Cargo Cult Science, 1974"),
    ("Lo que no puedo crear, no lo entiendo.",
     "Richard Feynman", "escrito en su pizarra al morir, 1988"),
    ("Prefiero tener preguntas que no pueden ser respondidas a tener respuestas que no pueden ser cuestionadas.",
     "Richard Feynman", "The Pleasure of Finding Things Out"),
    ("La simplicidad es la máxima sofisticación.",
     "Leonardo da Vinci", "atribuida"),
    ("El pensamiento no es más que un relámpago entre dos largas noches, pero ese relámpago lo es todo.",
     "Henri Poincaré", "El valor de la ciencia"),
    ("A veces, las personas de las que nadie imagina nada son las que hacen las cosas que nadie puede imaginar.",
     "Alan Turing", "atribuida"),
    ("Solo podemos ver poco del futuro, pero lo suficiente para darnos cuenta de que hay mucho por hacer.",
     "Alan Turing", "Computing Machinery and Intelligence"),
    ("La máquina analítica teje patrones algebraicos igual que el telar de Jacquard teje flores y hojas.",
     "Ada Lovelace", "Notas sobre la máquina analítica de Babbage, 1843"),
    ("La información es la resolución de la incertidumbre.",
     "Claude Shannon", "A Mathematical Theory of Communication"),
    ("La inteligencia es la capacidad de adaptarse al cambio.",
     "Stephen Hawking", "discurso de graduación en Oxford"),
    ("Por muy difícil que parezca la vida, siempre hay algo que puedes hacer y en lo que puedes tener éxito.",
     "Stephen Hawking", "atribuida"),
    ("En matemáticas no se comprenden las cosas, uno simplemente se acostumbra a ellas.",
     "John von Neumann", "atribuida"),
    ("La tarea no es tanto ver lo que nadie ha visto aún, sino pensar lo que nadie ha pensado todavía sobre lo que todo el mundo ve.",
     "Erwin Schrödinger", "atribuida"),
    ("Lo que observamos no es la naturaleza en sí misma, sino la naturaleza expuesta a nuestro método de interrogación.",
     "Werner Heisenberg", "Física y filosofía"),
    ("Un experto es una persona que ha cometido todos los errores que se pueden cometer en un campo muy estrecho.",
     "Niels Bohr", "atribuida"),

    # =========================================================================
    # OFICIO, INGENIERÍA, CÓDIGO Y DISCIPLINA PRÁCTICA
    # =========================================================================
    ("Los programas deben escribirse para que los lean las personas y solo de forma incidental para que los ejecuten las máquinas.",
     "Abelson y Sussman", "Structure and Interpretation of Computer Programs"),
    ("La informática no trata de los ordenadores más de lo que la astronomía trata de los telescopios.",
     "Edsger W. Dijkstra", "atribuida"),
    ("La simplicidad es un prerrequisito para la fiabilidad.",
     "Edsger W. Dijkstra", "EWD498"),
    ("Si el depurar es el proceso de eliminar errores, entonces programar debe ser el proceso de introducirlos.",
     "Edsger W. Dijkstra", "atribuida"),
    ("La optimización prematura es la raíz de todos los males.",
     "Donald Knuth", "Structured Programming with go to Statements"),
    ("La ciencia es lo que entendemos lo suficiente como para explicárselo a una computadora. El arte es todo lo demás.",
     "Donald Knuth", "A = B, prólogo"),
    ("Un lenguaje que no cambia tu manera de pensar sobre la programación no merece la pena conocerlo.",
     "Alan Perlis", "Epigrams on Programming"),
    ("Con suficientes ojos, todos los errores son evidentes.",
     "Eric S. Raymond", "La catedral y el bazar"),
    ("Hablar es barato. Enséñame el código.",
     "Linus Torvalds", "lista de correo del kernel de Linux, 2000"),
    ("La mayoría de los buenos programadores programan no porque esperan que les paguen, sino porque es divertido.",
     "Linus Torvalds", "atribuida"),
    ("Depurar es el doble de difícil que escribir el código en primer lugar. Por tanto, si escribes el código tan astutamente como puedes, por definición no eres lo bastante inteligente para depurarlo.",
     "Brian Kernighan", "The Elements of Programming Style"),
    ("No te limites a parchar el error: muestra por qué ocurrió y evita que vuelva a suceder.",
     "Brian Kernighan y Rob Pike", "The Practice of Programming"),
    ("No puedes confiar en código que no hayas creado tú mismo por completo.",
     "Ken Thompson", "Reflections on Trusting Trust"),
    ("UNIX es básicamente un sistema operativo simple, pero tienes que ser un genio para entender su simplicidad.",
     "Dennis Ritchie", "atribuida"),
    ("Solo hay dos tipos de lenguajes: aquellos de los que la gente se queja y aquellos que nadie usa.",
     "Bjarne Stroustrup", "The C++ Programming Language"),
    ("La frase más peligrosa del lenguaje es: 'Siempre lo hemos hecho así'.",
     "Grace Hopper", "atribuida"),
    ("Cualquier tonto puede escribir código que un ordenador entienda. Los buenos programadores escriben código que los humanos pueden entender.",
     "Martin Fowler", "Refactoring"),
    ("Haz que funcione, haz que sea correcto, haz que sea rápido.",
     "Kent Beck", "Extreme Programming Explained"),
    ("Nueve mujeres no pueden tener un bebé en un mes.",
     "Frederick Brooks", "The Mythical Man-Month"),
    ("El diseño no es solo cómo se ve y cómo se siente. El diseño es cómo funciona.",
     "Steve Jobs", "entrevista en The New York Times, 2003"),
    ("Menos, pero con mejor ejecución.",
     "Dieter Rams", "Diez principios del buen diseño"),
    ("Escribo para descubrir qué estoy pensando.",
     "Joan Didion", "Por qué escribo"),
    ("No te elevas al nivel de tus metas; caes al nivel de tus sistemas.",
     "James Clear", "Hábitos Atómicos"),
    ("Cada acción que tomas es un voto por el tipo de persona en la que deseas convertirte.",
     "James Clear", "Hábitos Atómicos"),
    ("La disciplina es el puente entre las metas y el logro.",
     "Jim Rohn", "atribuida"),
    ("En Dios confiamos; todos los demás deben traer datos.",
     "W. Edwards Deming", "atribuida"),
    ("Si no puedes describir lo que estás haciendo como un proceso, no sabes lo que estás haciendo.",
     "W. Edwards Deming", "Out of the Crisis"),
    ("Mide dos veces, corta una.",
     "Proverbio de taller y carpintería", "tradicional"),
    ("La herramienta no hace al maestro, pero el maestro cuida su herramienta.",
     "Proverbio de artesanos", "tradicional"),
    ("Un buen mecánico no repara lo que está roto: previene lo que está a punto de fallar.",
     "Máxima de mantenimiento", "tradicional"),
    ("Un mar en calma nunca hizo experto a un marinero.",
     "Proverbio de navegación", "tradicional"),
    ("Rápido es lento, pero sin pausas.",
     "Proverbio de maestría Kaizen", "tradicional"),
    ("La gota horada la piedra no por su fuerza, sino por su constancia.",
     "Ovidio", "Epistulae ex Ponto"),
    ("Lo que no puedo crear, no lo entiendo.",
     "Richard Feynman", "Última anotación en su pizarra, 1988"),
    ("El primer principio es que no debes engañarte a ti mismo, y tú eres la persona más fácil de engañar.",
     "Richard Feynman", "Discurso de graduación en Caltech, 1974"),
    ("Solo podemos ver un poco del futuro, pero lo suficiente para darnos cuenta de que hay mucho que hacer.",
     "Alan Turing", "Computing Machinery and Intelligence, 1950"),
    ("La información es la resolución de la incertidumbre.",
     "Claude Shannon", "A Mathematical Theory of Communication, 1948"),
    ("Ese cerebro mío es algo más que meramente mortal, como el tiempo lo demostrará.",
     "Ada Lovelace", "Carta a su madre Lady Byron, 1843"),
    ("Los encantos de esta sublime ciencia, las matemáticas, solo se revelan a aquellos que tienen el valor de profundizar en ella.",
     "Carl Friedrich Gauss", "Correspondencia científica"),
    ("El pensamiento no es más que un relámpago en medio de una larga noche. Pero ese relámpago lo es todo.",
     "Henri Poincaré", "El valor de la ciencia, 1905"),
    ("Nada en la vida debe ser temido, solamente comprendido. Ahora es el momento de comprender más, para temer menos.",
     "Marie Curie", "atribuida"),
    ("La simplicidad es la máxima sofisticación.",
     "Leonardo da Vinci", "atribuida"),
    ("El presente es de ellos; el futuro, por el cual realmente he trabajado, es mío.",
     "Nikola Tesla", "Declaraciones sobre la corriente alterna"),
    ("Tienes poder sobre tu mente, no sobre los acontecimientos. Date cuenta de esto y encontrarás la fuerza.",
     "Marco Aurelio", "Meditaciones"),
    ("No nos atrevemos a muchas cosas porque son difíciles; son difíciles porque no nos atrevemos a hacerlas.",
     "Séneca", "Cartas a Lucilio"),
    ("El verdadero viaje del aprendizaje consiste no en buscar nuevas tierras, sino en mirar con nuevos ojos.",
     "Marcel Proust", "En busca del tiempo perdido"),
    ("Un experto es una persona que ha cometido todos los errores que pueden cometerse en un campo muy estrecho.",
     "Niels Bohr", "atribuida"),
    ("No he fracasado. He encontrado 10.000 formas que no funcionan.",
     "Thomas Alva Edison", "atribuida"),
    ("La ciencia es el gran antídoto contra el veneno del entusiasmo y la superstición.",
     "Adam Smith", "La riqueza de las naciones, 1776"),
    ("En algún lugar, algo increíble está esperando ser descubierto.",
     "Carl Sagan", "atribuida"),
    ("Saber que no sabemos lo que no sabemos es el comienzo del conocimiento.",
     "Lao-Tsé", "Tao Te King"),
    ("La duda es el principio de la sabiduría.",
     "Aristóteles", "Metafísica"),
    ("Todo lo que una persona puede imaginar, otras personas lo pueden hacer realidad.",
     "Julio Verne", "De la Tierra a la Luna"),
    ("Dadme un punto de apoyo y moveré el mundo.",
     "Arquímedes", "citado por Pappus de Alejandría"),
    ("Defiende tu derecho a pensar, porque incluso pensar de manera errónea es mejor que no pensar.",
     "Hipatia de Alejandría", "atribuida"),
    ("La música es el placer que experimenta la mente humana al contar sin ser consciente de que está contando.",
     "Gottfried Wilhelm Leibniz", "Carta a Christian Goldbach, 1712"),
    ("Si tuviera que nombrar a las matemáticas contemporáneas más notables, mencionaría a Emmy Noether.",
     "Albert Einstein", "Carta al New York Times, 1935"),
    ("Hablar es barato. Enséñame el código.",
     "Linus Torvalds", "Mensaje en Linux Kernel Mailing List, 2000"),
    ("UNIX es básicamente un sistema operativo sencillo, pero tienes que ser un genio para entender la sencillez.",
     "Dennis Ritchie", "atribuida"),
    ("La optimización prematura es la raíz de todos los males en programación.",
     "Donald Knuth", "Structured Programming with go to Statements, 1974"),
    ("El cosmos está dentro de nosotros. Estamos hechos de materia estelar. Somos el medio para que el cosmos se conozca a sí mismo.",
     "Carl Sagan", "Cosmos, 1980"),
    ("La mayor dificultad del mundo no es que la gente acepte nuevas ideas, sino que olvide las viejas.",
     "John Maynard Keynes", "La teoría general del empleo, el interés y el dinero, 1936"),
    ("No nos afecta lo que nos sucede, sino lo que nos decimos sobre lo que nos sucede.",
     "Epicteto", "Enquiridión"),
    ("En medio del caos, también está la oportunidad.",
     "Sun Tzu", "El arte de la guerra"),
    ("El verdadero creador no busca la admiración de la masa, sino la aprobación de su propia conciencia.",
     "Nikola Tesla", "Mis inventos, 1919"),
    ("El corazón tiene sus razones, que la razón no conoce.",
     "Blaise Pascal", "Pensamientos, 1670"),
    ("La naturaleza utiliza la menor cantidad posible de todo.",
     "Johannes Kepler", "Harmonices Mundi, 1619"),
    ("Nada es demasiado maravilloso para ser cierto, si es consistente con las leyes de la naturaleza.",
     "Michael Faraday", "Anotaciones de laboratorio"),
    ("En la ciencia pura, el progreso no consiste en acumular hechos, sino en la conexión profunda entre ellos.",
     "James Clerk Maxwell", "Discursos científicos"),
    ("En matemáticas no se comprenden las cosas; uno simplemente se acostumbra a ellas.",
     "John von Neumann", "citado en The Mathematical Intelligencer"),
    ("Es más fácil pedir perdón que pedir permiso.",
     "Grace Hopper", "atribuida"),
    ("Como seres humanos, podemos lograr cualquier cosa si nos comprometemos con la verdad y la precisión.",
     "Katherine Johnson", "Entrevistas NASA"),
    ("El código limpio siempre parece que fue escrito por alguien que se preocupaba profundamente.",
     "Robert C. Martin", "Clean Code, 2008"),
    ("El que conoce a los demás es sabio; el que se conoce a sí mismo está iluminado.",
     "Lao-Tsé", "Tao Te King"),
    ("El hombre sabio busca lo que desea en sí mismo; el hombre común lo busca en los demás.",
     "Confucio", "Analectas"),
    ("El secreto de una buena vejez no es otra cosa que un pacto honrado con la soledad.",
     "Gabriel García Márquez", "Cien años de soledad"),
    ("No hay medicina que cure lo que no cura la felicidad.",
     "Gabriel García Márquez", "Del amor y otros demonios"),
    ("Uno no es lo que es por lo que escribe, sino por lo que ha leído.",
     "Jorge Luis Borges", "Discusión"),
    ("Ordenar una biblioteca es una manera silenciosa de ejercer el arte de la crítica.",
     "Jorge Luis Borges", "Prólogos"),
    ("El verbo leer, como el verbo amar y el verbo soñar, no soporta el modo imperativo.",
     "Jorge Luis Borges", "Siete noches"),
    ("Cualquier destino, por largo y complicado que sea, consta en realidad de un solo momento: cuando el hombre sabe quién es.",
     "Jorge Luis Borges", "El Aleph"),
    ("Andábamos sin buscarnos pero sabiendo que andábamos para encontrarnos.",
     "Julio Cortázar", "Rayuela"),
    ("Nada está perdido si se tiene el valor de proclamar que todo está perdido y hay que empezar de nuevo.",
     "Julio Cortázar", "Rayuela"),
    ("Tienes poder sobre tu mente, no sobre los acontecimientos externos. Entiende esto y hallarás tu fuerza.",
     "Marco Aurelio", "Meditaciones"),
    ("La mejor venganza es ser diferente de aquel que causó el daño.",
     "Marco Aurelio", "Meditaciones"),
    ("Cuando te levantes por la mañana, piensa en el precioso privilegio de estar vivo, respirar, pensar y aprender.",
     "Marco Aurelio", "Meditaciones"),
    ("El impedimento a la acción avanza la acción. Lo que se interpone en el camino se convierte en el camino.",
     "Marco Aurelio", "Meditaciones"),
    ("No es que tengamos poco tiempo, sino que perdemos mucho.",
     "Séneca", "De la brevedad de la vida"),
    ("La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.",
     "Séneca", "Epístolas a Lucilio"),
    ("Mientras enseñamos, aprendemos.",
     "Séneca", "Epístolas a Lucilio"),
    ("No nos afecta lo que nos sucede, sino lo que pensamos acerca de lo que nos sucede.",
     "Epicteto", "Enquiridión"),
    ("Solo los que se educan son verdaderamente libres.",
     "Epicteto", "Disertaciones"),
    ("En medio del invierno, descubrí que había dentro de mí un verano invencible.",
     "Albert Camus", "El verano"),
    ("La verdadera generosidad hacia el porvenir consiste en entregarlo todo al presente.",
     "Albert Camus", "El hombre rebelde"),
    ("Aquel que tiene un porqué para vivir se puede enfrentar a casi todos los «cómos».",
     "Friedrich Nietzsche", "El crepúsculo de los ídolos"),
    ("El conocimiento se puede transmitir, pero la sabiduría no. Se la puede hallar y vivir, pero no enseñar.",
     "Hermann Hesse", "Siddhartha"),
    ("En algún lugar, algo increíble está esperando ser descubierto.",
     "Carl Sagan", "Cosmos"),
    ("La imaginación nos llevará a mundos que nunca fueron. Pero sin ella no iremos a ninguna parte.",
     "Carl Sagan", "Cosmos"),
    ("Somos una forma en que el cosmos se conoce a sí mismo.",
     "Carl Sagan", "Cosmos"),
    ("Lo primero es no engañarte a ti mismo, y tú eres la persona más fácil de engañar.",
     "Richard Feynman", "¿Está usted de broma, Sr. Feynman?"),
    ("Prefiero tener preguntas que no pueden ser respondidas que respuestas que no pueden ser cuestionadas.",
     "Richard Feynman", "El placer de descubrir las cosas"),
    ("La autoeducación es, estoy convencido, el único tipo de educación que existe.",
     "Isaac Asimov", "Memorias"),
    ("Cualquier tecnología suficientemente avanzada es indistinguible de la magia.",
     "Arthur C. Clarke", "Perfiles del futuro"),
    ("No tienes que quemar libros para destruir una cultura. Solo haz que la gente deje de leerlos.",
     "Ray Bradbury", "Fahrenheit 451"),
    ("No hay barrera, cerradura ni cerrojo que puedas imponer a la libertad de mi mente.",
     "Virginia Woolf", "Una habitación propia"),
    ("Hablar es fácil. Muéstrame el código.",
     "Linus Torvalds", "Linux Kernel Archives"),
    ("La optimización prematura es la raíz de todos los males en la programación.",
     "Donald Knuth", "Structured Programming"),
    ("La ciencia es lo que entendemos tan bien como para explicárselo a una máquina; el arte es todo lo demás.",
     "Donald Knuth", "Selected Papers on Computer Science"),
    ("En medio del caos, también hay una oportunidad.",
     "Sun Tzu", "El arte de la guerra"),
    ("Los dos guerreros más poderosos son la paciencia y el tiempo.",
     "León Tolstói", "Guerra y paz"),
    ("No hay nada más poderoso que una idea a la que le ha llegado su tiempo.",
     "Víctor Hugo", "Los miserables"),
    ("Dar un paso nuevo, pronunciar una palabra nueva, es lo que la gente teme más.",
     "Fiódor Dostoievski", "Crimen y castigo"),
]


def aleatoria(evitar=()):
    """Una cita al azar, esquivando las últimas que ya se dijeron."""
    libres = [c for c in CITAS if c[0] not in evitar] or CITAS
    return random.choice(libres)
